services:
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - /srv:/srv
      - /source:/source
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/config/.gitconfig
      - ~/.git-credentials:/config/.git-credentials
      - ./config:/config #Map config to persist extensions
    environment:
      # General environment variables
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
      # Application specific variables
      DEFAULT_WORKSPACE: /source
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:code-server-python3
