services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /source/custom_components:/config/custom_components
    environment:
      TZ: Europe/Amsterdam
    cap_add:
      - NET_ADMIN
      - NET_RAW